name: Deploy
on:
  push:
    branches:
      - source
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Minify CSS, HTML, and JS
        run: |
          yarn add https://github.com/xxczaki/minifly
          cd public
          yarn run minifly -i "/assets/favicon.png,/assets/img" -m "" -o .

      - name: Deploy
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          deploy-branch: master
          repo-token: ${{ secrets.GH_PAT }}
          site-directory: public
