name: Deploy

on:
  push:
    branches:
    - source

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@master
    -
      uses: actions/setup-node@v1
    -
      run: |
        npm i -g inliner-terser
        sh -c 'cd public && cat index.html | inliner-terser -im > index.html.min && mv index.html.min index.html'