name: Deploy

on:
  push:
    branches:
      - source

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Minify
        run: |
          export PATH="$PATH:$HOME/.config/yarn/global/node_modules/.bin"
          yarn global add minifly
          cd public
          minifly -m "" -o ""

      - name: Deploy
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          deploy-branch: master
          repo-token: ${{ secrets.GH_PAT }}
          site-directory: public
