name: Deploy
on:
  push:
    branches:
      - source
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: |
          npm i -g Ryank02/minifly
          cd public
          minifly -i "/assets/favicon.png,/assets/img" -m "" -o .
      - uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          deploy-branch: master
          repo-token: ${{ secrets.GH_PAT }}
          site-directory: public/
