name: Deploy

on:
  push:
    branches:
      - source

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Minify
        run: |
          export PATH="$PATH:$HOME/.config/yarn/global/node_modules/.bin"
          yarn global add minify
          cd public
          minify index.html > index.html
          minify over-mij/index.html > over-mij/index.html
          minify projecten/index.html > projecten/index.html
          minify contact/index.html > contact/index.html
          minify assets/css/style.css > assets/css/style.css
          minify assets/js/script.js > assets/js/script.js

      - name: Deploy
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          deploy-branch: master
          repo-token: ${{ secrets.GH_PAT }}
          site-directory: public
