name: Deploy

on:
  push:
    branches:
      - source

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Minify
        run: |
          export PATH="$PATH:$HOME/.config/yarn/global/node_modules/.bin"
          yarn global add minifly
          find public -type d -exec sh -c 'cd {} && minifly -i "*.gif,*.jpg,*.png,*.svg" -m "" -o .' \;

      - name: Discord validation
        run: |
          cd public
          mkdir .well-known
          cd .well-known
          echo -n "dh=f770b8997c7635ec886d978946f40e75e1600a96" | cat > discord

      - name: Deploy
        uses: actions/deploy-pages@v2
        with:
          token: ${{ github.token }}
