name: Deploy
on:
  push:
    branches:
      - source
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Minify CSS, HTML, and JS
        run: |
          export PATH="$PATH:$HOME/.config/yarn/global/node_modules/.bin"
          yarn global add minifly
          find public -type f -iname "*.html" -exec sed -i 's+<script src="/assets/js/swup.min.js"></script>+\ +g' {} \;
          find public -type d -exec sh -c 'cd {} && minifly -i "*.gif,*.jpg,*.png,*.svg" -m "" -o .' \;
          cd public/assets/js
          cat script.js >> swup.min.js
          mv swup.min.js script.js

      - name: Deploy
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          deploy-branch: master
          repo-token: ${{ secrets.GH_PAT }}
          site-directory: public
