name: Deploy
on:
  push:
    branches:
    - source
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm i -g inliner-terser
        sh -c 'cd public && cat index.html | inliner-terser -im > index.html.min && mv index.html.min index.html'
    - uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
      with:
        deploy-branch: master
        site-directory: public/
