name: Deploy
on:
  push:
    branches:
      - source
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: |
          npm i -g minifly
          cd public
          minifly -i "*.min.*" -o ./
          rename ".min" "" *.min.*
          # find public \( -iname *.css -o -iname *.html -o -iname *.js \) ! \( -iname "*.min.*" \) -exec sh -c 'cat $0 | minify > $0' {} \;
      - uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          deploy-branch: master
          repo-token: ${{ secrets.GH_PAT }}
          site-directory: public/
