name: Deploy to pages

on:
  push:
    branches:
      - source

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: public

      - name: Minify
        run: |
          export PATH="$PATH:$HOME/.config/yarn/global/node_modules/.bin"
          yarn global add minifly
          find public -type d -exec sh -c 'cd {} && minifly -i "*.gif,*.jpg,*.png,*.svg" -m "" -o .' \;

      - name: Discord validation
        run: |
          cd public
          mkdir .well-known
          cd .well-known
          echo -n "dh=f770b8997c7635ec886d978946f40e75e1600a96" | cat > discord

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: '.'

      - name: Deploy
        uses: actions/deploy-pages@v2
