name: Deploy to pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Minify
        run: |
          export PATH="$PATH:$HOME/.config/yarn/global/node_modules/.bin"
          yarn global add minifly
          find public -type d -exec sh -c 'cd {} && minifly -i "*.gif,*.jpg,*.png,*.svg" -m "" -o .' \;

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'public'

      - name: Deploy
        uses: actions/deploy-pages@v4.0.5
